# Generated by Django 5.0.6 on 2024-05-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
